<?php

require('func.php');

INIT_TEMPLATE_PATH('__error');

$c = RET_INT_GET(ARGUMENT_ERROR);
$t = sprintf(ERROR_TITLE, $c);

$m[ERROR_CODE_UNKNOW]			= ERROR_UNKNOW;
$m[ERROR_CODE_LOAD_STORES]		= ERROR_LOAD_STORES;
$m[ERROR_CODE_UNKNOW_ORDER_MODE]	= ERROR_UNKNOW_ORDER_MODE;
$m[ERROR_CODE_NOT_SAME_ADDRESS]		= ERROR_NOT_SAME_ADDRESS;
$m[ERROR_CODE_EMPTY_ID]			= ERROR_EMPTY_ID;
$m[ERROR_CODE_UNKNOW_ID]		= ERROR_UNKNOW_ID;
$m[ERROR_CODE_WRITE_FILE_FAIL]		= ERROR_WRITE_FILE_FAIL;
$m[ERROR_CODE_EMPTY_TABLE_NAME]		= ERROR_EMPTY_TABLE_NAME;
$m[ERROR_CODE_EMPTY_TABLE_ADDRESS]	= ERROR_EMPTY_TABLE_ADDRESS;
$m[ERROR_CODE_EMPTY_CATEGORY_NAME]	= ERROR_EMPTY_CATEGORY_NAME;
$m[ERROR_CODE_EMPTY_FLAVOR_NAME]	= ERROR_EMPTY_FLAVOR_NAME;
$m[ERROR_CODE_EMPTY_MEMBER_NAME]	= ERROR_EMPTY_MEMBER_NAME;
$m[ERROR_CODE_EMPTY_ADDITIONAL_NAME]	= ERROR_EMPTY_ADITIONAL_NAME;
$m[ERROR_CODE_EMPTY_MEAL_NAME]		= ERROR_EMPTY_MEAL_NAME;
$m[ERROR_CODE_EMPTY_TAG_NAME]		= ERROR_EMPTY_TAG_NAME;
$m[ERROR_CODE_UNKNOW_TAG]		= ERROR_UNKNOW_TAG;
$m[ERROR_CODE_UNKNOW_CATEGORY]		= ERROR_UNKNOW_CATEGORY;
$m[ERROR_CODE_UNKNOW_MEAL]		= ERROR_UNKNOW_MEAL;
$m[ERROR_CODE_UNKNOW_TABLE]		= ERROR_UNKNOW_TABLE;
$m[ERROR_CODE_ZERO_PAY]			= ERROR_ZERO_PAY;
$m[ERROR_CODE_ZERO_TOTAL]		= ERROR_ZERO_TOTAL;
$m[ERROR_CODE_PAY_UNDER_TOTAL]		= ERROR_PAY_UNDER_TOTAL;
$m[ERROR_CODE_NOT_MP3]			= ERROR_NOT_MP3;
$m[ERROR_CODE_ID_IS_TIMEOUT]		= ERROR_ID_IS_TIMEOUT;
$m[ERROR_CODE_EMPTY_ACCOUNT]		= ERROR_EMPTY_ACCOUNT;
$m[ERROR_CODE_EMPTY_PASSWORD]		= ERROR_EMPTY_PASSWORD;
$m[ERROR_CODE_NOT_SAME_PASSWORD]	= ERROR_NOT_SAME_PASSWORD;
$m[ERROR_CODE_NOT_SAME_MODULE]		= ERROR_NOT_SAME_MODULE;
$m[ERROR_CODE_TEMPLATE_CONFIG]		= ERROR_TEMPLATE_CONFIG;
$m[ERROR_CODE_EMPTY_TEMPLATE_PATH]	= ERROR_EMPTY_TEMPLATE_PATH;
$m[ERROR_CODE_OVER_TMP_LIMIT]		= ERROR_OVER_TMP_LIMIT;
$m[ERROR_CODE_NOT_ZIP]			= ERROR_NOT_ZIP;

if (!isset($m[$c])) $c = 0;

LOAD_TEMPLATE_PAGE('error_page', $t);

$block = RET_TEMPLATE_CONTENT('error_content');
$ra = array(
	'error_id'	=> $c
	,'error_msg'	=> $m[$c]
);
INSERT_TEMPLATE_BLOCK(RET_REPLACED_TEMPLATE($block, $ra));

DUMP_TEMPLATE_PAGE();
