<?php

define('CONFIG_ORDER_TO_KDS_SOUND', '');

define('CONFIG_KDS_AUTO_PRINT', '');
define('CONFIG_KDS_REFRESH_SECONDS', 90);
define('CONFIG_KDS_ROWS_EACH_PAGE', 6);
define('CONFIG_KDS_DISABLE_SOUND', '');
define('CONFIG_KDS_SOUND_VOLUME', 0.1);
define('CONFIG_KDS_TIMEOUT_MINUTES_0', 5);
define('CONFIG_KDS_TIMEOUT_COLOR_0', '#99cc00');
define('CONFIG_KDS_TIMEOUT_MINUTES_1', 10);
define('CONFIG_KDS_TIMEOUT_COLOR_1', '#ffbb33');
define('CONFIG_KDS_TIMEOUT_MINUTES_2', 15);
define('CONFIG_KDS_TIMEOUT_COLOR_2', '#ff6868');

define('CONFIG_HISTORY_KEEP_ROWS', '12');