<?php

if (!isset($id_category)) exit();

ORDER_BUILD_GROUP_LINE_IDS();

LOAD_TEMPLATE_PAGE('order_page', ORDER_CAPTION_MEAL);
INSERT_TEMPLATE_BLOCK(ORDER_BLOCK_SECTION_LIST());

INSERT_TEMPLATE_BLOCK(ORDER_BLOCK_LIST_GROUPS());
INSERT_TEMPLATE_BLOCK(ORDER_BLOCK_LIST_RANDOM_MEALS());

INSERT_TEMPLATE_BLOCK(ORDER_BLOCK_FOOTER());
DUMP_TEMPLATE_PAGE();
