<?php

if (!isset($id)) exit();

ORDER_BUILD_GROUP_LINE_IDS();
ORDER_BUILD_ITEM_LINE_IDS();
$title = $row_meal[MEAL_NAME].RET_ITEM_EN($row_meal[MEAL_NAME_EN]).' $'.$row_meal[MEAL_PRICE];
$action = $THIS_WEB_URL;
APEND_URL_ARGUMENT($action, POST_CATEGORY, $row_category[CATEGORY_ID]);

LOAD_TEMPLATE_PAGE('order_page', $title);
INSERT_TEMPLATE_BLOCK(ORDER_BLOCK_SECTION_LIST());

INSERT_TEMPLATE_BLOCK(ORDER_BLOCK_NAV_ITEM());
INSERT_TEMPLATE_BLOCK(ORDER_BLOCK_MEAL_INFO($title, $action));
INSERT_TEMPLATE_BLOCK(ORDER_BLOCK_LIST_CATEGORY_MEALS($row_category[CATEGORY_NAME].RET_ITEM_EN($row_category[CATEGORY_NAME_EN])));
INSERT_TEMPLATE_BLOCK(ORDER_BLOCK_LIST_GROUPS());

INSERT_TEMPLATE_BLOCK(ORDER_BLOCK_FOOTER());
DUMP_TEMPLATE_PAGE();