<?php

if (!isset($the_operation_2)) exit();

$name = RET_STR_POST(POST_NAME);

if ('' == $name) E_TO(ERROR_CODE_EMPTY_MEMBER_NAME);

$id = md5(PREFIX_TITLE.date('YmdHis').$name);

$row[MB_ADDITIONAL_ID]			= $id;
$row[MB_ADDITIONAL_NAME]		= $name;
$row[MB_ADDITIONAL_PHOTO]		= RET_UPLOAD_PHOTO($the_folder, $id);
$row[MB_ADDITIONAL_PRICE]		= RET_INT_POST(POST_PRICE);
$row[MB_ADDITIONAL_DESCRIPTION]		= RET_STR_POST(POST_DESCRIPTION);
$row[MB_ADDITIONAL_NAME_EN]		= RET_STR_POST(POST_NAME_EN);
$row[MB_ADDITIONAL_DESCRIPTION_EN]	= RET_STR_POST(POST_DESCRIPTION_EN);
$row[MB_ADDITIONAL_NU_1]		= '';

SCALE_MEMBER_PHOTO($id, $row[MB_ADDITIONAL_PHOTO]);

if (!INSERT_DB($the_db_2, $row)) E_TO(ERROR_CODE_WRITE_FILE_FAIL);

P_TO($THIS_WEB_URL);
